// runtime.h
#ifndef RUNTIME_H
#define RUNTIME_H

#include "compiler.h"
#include <vector>
#include <string>

/**
 * @brief Runtime class to execute the Intermediate Representation (IR) code
 * generated by the compiler.
 */
class Runtime {
private:
    std::vector<IRNode> ir; ///< Intermediate representation of source code

public:
    /**
     * @brief Constructor
     * @param ir_code Vector of IRNode representing compiled instructions
     */
    Runtime(const std::vector<IRNode>& ir_code);

    /**
     * @brief Executes the provided IR instructions
     */
    void execute();
};

#endif // RUNTIME_H